export enum ExpectedErrorCode {
  FIELD_VALIDATION_ERROR = 'FIELD_VALIDATION_ERROR',
  MULTIFIELD_VALIDATION_ERROR = 'MULTIFIELD_VALIDATION_ERROR',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  INVALID_CREDENTIAL_ERROR = 'INVALID_CREDENTIAL_ERROR',
  FORBIDDEN_ERROR = 'FORBIDDEN_ERROR',
  INVALID_STATE_ERROR = 'INVALID_STATE_ERROR',
}
